name: Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          version: 14.x
      - name: Run build
        run: |
          npm i
          npm i @nestjs/common @nestjs/core reflect-metadata
          npm run build
