name: Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
          scope: "@shaka-time"
      - name: Run build
        run: |
          npm i
          npm run build    
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist    
